### PR TITLE
Fix Contacts Export vCard Template

### LINKED ISSUE #73: 匯出 vcard nickname 會是空的
vcard 檔案結果大致為

```
BEGIN:VCARD
VERSION:4.0

FN:
NICKNAME:
ORG:COSCUP 2016 
TITLE:總召
PHOTO;VALUE=uri:https://secure.gravatar.com/avatar/xxxxx
TEL;TYPE=cell:09XXXXXXXX
EMAIL:XXXXXXXX@gmail.com
END:VCARD
```

關鍵 commit 應該是在這一筆 586cc725a9cd63ee8566c7cd1a0528d590586b66

### PR DESCRIPTION
**Pull request by Sea-n**
Fix #73 
修正 NICKNAME 欄位
新增 NOTE 欄位

### CODE REVIEW

**Comment by rschiang** [comment]
@Sea-n Thanks for contribution!
The `name` was a property which will fallback to account name (please refer to `users.models` in advance), so changing them into `display_name` is not feasible; 
the `title` field already indicates the identity of individual (e.g. 「行政組員」), while `groups` is a database cursor, thus cannot be printed out directly.

Please adjust the PR to fit these functionalities. Thanks!

**Comment by rschiang** [comment]
You could refer to #73 for possible advice (in Chinese)

**Comment by pcchou** [comment]
Thanks @Sea-n for your contribution!

Just so you know,
I'll merge it and take care of the rest later today.

**Comment by rschiang** [comment]
Fixed in ea54abf32417934a97951f3245a2d38626307eef. Thanks for all contributions made. :)

**Pull request closed without merging**
